using STOREEX.Models; using System; using System.Linq; using System.Web.Mvc;
namespace STOREEX.Controllers {
 [Authorize] public class ProductsController:Controller { readonly StoreexDb db=new StoreexDb(); const int C=1; public ActionResult Index(){return View(db.Products.Where(x=>x.CompanyId==C).OrderBy(x=>x.Name).ToList());} [HttpPost,ValidateAntiForgeryToken] public ActionResult Save(Product m){if(m.Id==0){m.CompanyId=C;m.CreatedAt=DateTime.UtcNow;db.Products.Add(m);}else{var x=db.Products.SingleOrDefault(z=>z.Id==m.Id&&z.CompanyId==C);if(x==null)return HttpNotFound();x.Name=m.Name;x.SKU=m.SKU;x.Barcode=m.Barcode;x.Description=m.Description;x.PurchasePrice=m.PurchasePrice;x.SalePrice=m.SalePrice;x.TaxRate=m.TaxRate;x.MinimumStock=m.MinimumStock;x.CategoryId=m.CategoryId;x.UnitId=m.UnitId;x.TrackStock=m.TrackStock;x.IsActive=m.IsActive;}db.SaveChanges();return RedirectToAction("Index");} protected override void Dispose(bool d){if(d)db.Dispose();base.Dispose(d);} }
 [Authorize] public class CustomersController:Controller { readonly StoreexDb db=new StoreexDb(); const int C=1; public ActionResult Index(){return View(db.Customers.Where(x=>x.CompanyId==C).OrderBy(x=>x.Name).ToList());} [HttpPost,ValidateAntiForgeryToken] public ActionResult Save(Customer m){if(m.Id==0){m.CompanyId=C;m.CreatedAt=DateTime.UtcNow;db.Customers.Add(m);}else{var x=db.Customers.SingleOrDefault(z=>z.Id==m.Id&&z.CompanyId==C);if(x==null)return HttpNotFound();x.Name=m.Name;x.BusinessNumber=m.BusinessNumber;x.FiscalNumber=m.FiscalNumber;x.Phone=m.Phone;x.Email=m.Email;x.Address=m.Address;x.City=m.City;x.CreditLimit=m.CreditLimit;x.IsActive=m.IsActive;}db.SaveChanges();return RedirectToAction("Index");} protected override void Dispose(bool d){if(d)db.Dispose();base.Dispose(d);} }
 [Authorize] public class InvoicesController:Controller { readonly StoreexDb db=new StoreexDb(); const int C=1; public ActionResult Index(){return View(db.Invoices.Where(x=>x.CompanyId==C).OrderByDescending(x=>x.InvoiceDate).Take(500).ToList());} public ActionResult Details(int id){var x=db.Invoices.Where(z=>z.CompanyId==C&&z.Id==id).Select(z=>z).FirstOrDefault();if(x==null)return HttpNotFound();return View(x);} protected override void Dispose(bool d){if(d)db.Dispose();base.Dispose(d);} }
 [Authorize] public class SuppliersController:Controller { readonly StoreexDb db=new StoreexDb(); const int C=1; public ActionResult Index(){return View(db.Suppliers.Where(x=>x.CompanyId==C).OrderBy(x=>x.Name).ToList());} protected override void Dispose(bool d){if(d)db.Dispose();base.Dispose(d);} }
 [Authorize] public class PurchasesController:Controller { readonly StoreexDb db=new StoreexDb(); const int C=1; public ActionResult Index(){return View(db.Purchases.Where(x=>x.CompanyId==C).OrderByDescending(x=>x.PurchaseDate).ToList());} protected override void Dispose(bool d){if(d)db.Dispose();base.Dispose(d);} }
 [Authorize] public class ExpensesController:Controller { readonly StoreexDb db=new StoreexDb(); const int C=1; public ActionResult Index(){return View(db.Expenses.Where(x=>x.CompanyId==C).OrderByDescending(x=>x.ExpenseDate).ToList());} protected override void Dispose(bool d){if(d)db.Dispose();base.Dispose(d);} }
 [Authorize] public class ReportsController:Controller { readonly StoreexDb db=new StoreexDb(); const int C=1; public ActionResult Index(){ViewBag.Sales=db.Invoices.Where(x=>x.CompanyId==C&&x.Status!=InvoiceStatus.Cancelled).Select(x=>(decimal?)x.Total).Sum()??0;ViewBag.Purchases=db.Purchases.Where(x=>x.CompanyId==C&&x.Posted).Select(x=>(decimal?)x.Total).Sum()??0;ViewBag.Receivables=db.Invoices.Where(x=>x.CompanyId==C).Select(x=>(decimal?)x.Balance).Sum()??0;return View();} protected override void Dispose(bool d){if(d)db.Dispose();base.Dispose(d);} }
 [Authorize] public class SettingsController:Controller { public ActionResult Index(){return View();} }
}